# Numpy

## List vs Numpy array

In [1]:
import numpy as np

### Defining List and Numpy array

In [13]:
A = [1,2,3] ##list
B = np.array([1,2,3]) ##numpy array

In [14]:
print(A)
print(B)

[1, 2, 3]
[1 2 3]


### Looping over each element

In [15]:
##looping over list
for i in A:
    print(i)

1
2
3


In [16]:
##Looping over numpy array
for i in B:
    print(i)

1
2
3


### Appending new element 

In [17]:
##Appending value in list
A.append(4)
print(A)


[1, 2, 3, 4]


In [18]:
## Another way of adding a value into List
A = A + [5]
print(A)

[1, 2, 3, 4, 5]


In [22]:
##Appending value in numpy array
B = np.append(B, [4,5])
print(B)

[1 2 3 4 5]


### Doubling each element

In [23]:
#Plus sign with list concatenate the list but with numpy array it do an vector addition

B + B

## if you have a 2D array or Matrix it will do matrix addition

array([ 2,  4,  6,  8, 10])

In [25]:
## For above type operation for list we have to perform this
A2 = []
for i in A:
    A2.append(i + i)
print(A2)

[2, 4, 6, 8, 10]


In [26]:
##getting 2 times a numpy array
print(2* B)

[ 2  4  6  8 10]


In [27]:
##But with list 2 times a list will make the list repeat the elements
print(2*A)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [28]:
## To get twice of each element in a list you have to loop each element and make them 2times

A2 = []
for i in A:
    A2.append(2*i)
print(A2)

[2, 4, 6, 8, 10]


### Squaring each element 

In [29]:
##Squaring each element 
##List
print(2**A) 
##line will give error

TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'list'

In [30]:
##To perform squaring in list we have to loop over each element
A2 = []
for i in A:
    A2.append(i*i)
    
print(A2)

[1, 4, 9, 16, 25]


In [31]:
##For numpy Array
print(B**B)

[   1    4   27  256 3125]


#### NOTE : Numpy array operations work element wise
#### Few more operations

In [32]:
np.sqrt(B)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [33]:
np.log(B)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [34]:
np.exp(B)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

#### To perform above operations on list you have to loop over each element and perform operation and save into another list

####  Conclusion : 
- To represent a vector numpy array is an more convienient option rather then list, as it is more easier to perform add, multiply, exponent and log operation on it.
- You can treat list like an array and numpy array as vector.
- To perform oprations on element in list you require to use for loops, which are slower operation.

## DOT Product

- there are 2 definitions of dot product
    - a.b = aTb (a transpose times b, here a and b both are vector or matrix)
    - a.b = |a||b|cosø
- the 2nd method is more difficult as compared to 1st one, infact 2nd method can be used to find the ø(theta, angle) between a and b.

In [35]:
A = np.array([1,2])
B = np.array([2,1])

In [45]:
##there are several ways to perform the dot product between 2 vectors
##Method1
dot = 0
for i, j in zip(A, B):
    dot += i*j
print("Method 1 => ", dot)

##Method2
print("Method 2 => ", np.sum(A*B))


##Method3
dot = np.dot(A, B)
print("Method 3 => ",dot)



Method 1 =>  4
Method 2 =>  4
Method 3 =>  4


In [59]:
## finding angel between 2 vectors
##Method1 
modA = np.sqrt(np.sum(A**A))
modB = np.sqrt(np.sum(B*B))

mod = modA * modB

theta = np.dot(A,B) / mod
print("Method1 => ")
print(theta)
print(np.arccos(theta))


##Method2
modA = np.linalg.norm(A)
modB = np.linalg.norm(B)

theta = np.dot(A, B) / (modA * modB)
print("Method2 => ")
print(theta)
print(np.arccos(theta))

Method1 => 
0.7999999999999998
0.6435011087932847
Method2 => 
0.7999999999999998
0.6435011087932847


## Matrices

- Matrix can be formed using numpy array of numpy array
- numpy has a matrix operation to create a matrix but we wont use it
- We can conver a matrix to numpy array using np.array operation

In [70]:
##creating an matrix
M1 = np.array([[1,2], [3,4]])
M1

array([[1, 2],
       [3, 4]])

In [69]:
##creating matrix using 2D list
M = [[1,2], [3,4]]
M

[[1, 2], [3, 4]]

In [65]:
##accessing elements
print(M1[1][0]) #1st row 0th column

3


In [66]:
##another way of accessing elements
print(M1[1,0])

3


In [68]:
##creating matrix using matrix operation
M2 = np.matrix([[1,2], [3,4]])
M2

matrix([[1, 2],
        [3, 4]])

In [71]:
##converting a matrix into numpy array
M2 = np.array(M2)

M2

array([[1, 2],
       [3, 4]])

In [74]:
##Matrix operations
print(np.transpose(M1))

print(M1.T)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


## Genarating Matrix and vectors

In [76]:
## vector of 0 and 1
##this will generate vector of all 1's of size 10
A = np.ones(10)
print(A)

##this will generate vector of all 0's of size 10
B = np.zeros(10)
print(B)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [78]:
##Matrices
M = np.zeros((10,10))
M

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
M = np.ones((10, 10))
M

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [88]:
##matrix with random values
R = np.random.random((10, 10))
R

##random numbers will be between 0 and 1

array([[0.08613534, 0.26985051, 0.35370535, 0.9853227 , 0.04018894,
        0.35056624, 0.22517978, 0.44937316, 0.71175703, 0.99460139],
       [0.80227954, 0.2525668 , 0.40066768, 0.86489904, 0.11801122,
        0.98205921, 0.06070597, 0.76745763, 0.38414116, 0.44040827],
       [0.24417607, 0.48720281, 0.59852066, 0.87415166, 0.87121408,
        0.92211572, 0.04586749, 0.21485213, 0.52174733, 0.79486751],
       [0.61356403, 0.1140426 , 0.29678057, 0.78407682, 0.33134033,
        0.91272754, 0.10445697, 0.3302753 , 0.79955591, 0.96526271],
       [0.15334611, 0.50435232, 0.64076122, 0.42626486, 0.40980219,
        0.18235856, 0.44322435, 0.49490305, 0.02032824, 0.99577619],
       [0.17444795, 0.36414006, 0.26594688, 0.07245327, 0.9836244 ,
        0.18461616, 0.67388615, 0.70523839, 0.48866194, 0.8794136 ],
       [0.68601082, 0.52215227, 0.65254767, 0.05518752, 0.89095917,
        0.65504664, 0.12141208, 0.89695525, 0.87842143, 0.420304  ],
       [0.42100055, 0.81961605, 0.2862695

In [87]:
## Matrix with random gaussian distributed number
G = np.random.randn(10,10)
G

array([[ 0.32718309, -0.2081856 ,  0.57678789,  0.49807054,  0.84059642,
         0.25335287, -2.10268592,  0.41681004, -0.011559  ,  0.6869594 ],
       [-0.89422203,  0.25250219,  1.05223165,  0.13563841,  0.31531557,
        -0.95925635,  1.60797028, -0.95603827, -0.31443736, -0.59643413],
       [-0.32863802,  1.00438238,  0.62091148, -0.04960114, -0.64434526,
         0.95151997,  1.05842801, -0.56886703, -0.15357229, -1.15424458],
       [ 0.13429364,  2.2725811 ,  0.15295362, -0.24158867,  0.10736024,
        -0.51573546, -0.96485928, -1.05179397, -0.18852885,  0.12828546],
       [-0.88528731, -1.15671247,  0.75646955, -0.7973901 , -0.06328702,
        -0.35377997,  0.0242147 ,  0.98779088, -0.03114168, -0.3017435 ],
       [-0.0260194 ,  1.02546163, -1.37109074, -1.73776309, -0.51748273,
        -1.5429753 , -1.04964728,  0.83976   , -0.00928976,  1.68426911],
       [-0.66881922, -0.49205554, -0.7218217 ,  1.05150395, -0.02648634,
         0.47831003, -0.58722744, -1.21007536

In [94]:
print(R.T) ##transpose
print(R.mean()) ##mean
print(R.std()) ##standard distribution
print(R.var()) ##variance

[[0.08613534 0.80227954 0.24417607 0.61356403 0.15334611 0.17444795
  0.68601082 0.42100055 0.48827295 0.17383856]
 [0.26985051 0.2525668  0.48720281 0.1140426  0.50435232 0.36414006
  0.52215227 0.81961605 0.72501294 0.06565285]
 [0.35370535 0.40066768 0.59852066 0.29678057 0.64076122 0.26594688
  0.65254767 0.28626957 0.38624546 0.0749617 ]
 [0.9853227  0.86489904 0.87415166 0.78407682 0.42626486 0.07245327
  0.05518752 0.00645602 0.53298273 0.03173213]
 [0.04018894 0.11801122 0.87121408 0.33134033 0.40980219 0.9836244
  0.89095917 0.03379396 0.95299561 0.53406911]
 [0.35056624 0.98205921 0.92211572 0.91272754 0.18235856 0.18461616
  0.65504664 0.54955179 0.50588984 0.13690426]
 [0.22517978 0.06070597 0.04586749 0.10445697 0.44322435 0.67388615
  0.12141208 0.42831357 0.64138582 0.07291988]
 [0.44937316 0.76745763 0.21485213 0.3302753  0.49490305 0.70523839
  0.89695525 0.68118452 0.52461686 0.34641221]
 [0.71175703 0.38414116 0.52174733 0.79955591 0.02032824 0.48866194
  0.87842143 

## Matrix Product

- the dimesnsions of 2 matrix should match
- the inner dimensions of the matrix should be same 
- For multiplication we use dot product of Row of matrix1 with Column of matrix2
- A(i,:).dot(B(:, j))

## Matrix Operations with Numpy

In [96]:
A = np.array([[1,2], [3,4]])

In [98]:
##inverse of a vector
invA = np.linalg.inv(A)
invA

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [103]:
##checking of inverse is calculated correctly
np.dot(A, invA)

##this should give identity matrix

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [104]:
##determinent of Matrix
np.linalg.det(A)

-2.0000000000000004

In [105]:
##diagonal of matrix
np.diag(A)

array([1, 4])

In [106]:
##creating matrix using the diagonal vector
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [107]:
##if you pass 2D array you will 2,2 matrix, if you pass 3D array you will get 3,3 matrix
np.diag([1,2,4])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [109]:
##trace of matrix, sum of diagnols of matrix
np.diag(A).sum()

5

In [110]:
np.trace(A)

5

In [114]:
##eigenvalues and eigenvectors
A = np.random.randn(100,3)
print(A.shape)

(100, 3)


In [122]:
cov = np.cov(A.T)

In [123]:
np.linalg.eigh(cov)

(array([0.8260182 , 0.99297028, 1.18500435]),
 array([[-0.26372467, -0.6795519 , -0.68458638],
        [ 0.90408636,  0.07327644, -0.42102068],
        [ 0.33626946, -0.72995875,  0.5950488 ]]))

In [125]:
np.linalg.eig(cov)

(array([1.18500435, 0.99297028, 0.8260182 ]),
 array([[-0.68458638, -0.6795519 , -0.26372467],
        [-0.42102068,  0.07327644,  0.90408636],
        [ 0.5950488 , -0.72995875,  0.33626946]]))

## Solving a linear equation

In [128]:
A = np.array([[1,2], [3,4]])
b = np.array([1,2])

In [130]:
x = np.dot(np.linalg.inv(A), b)
x

array([0. , 0.5])

In [131]:
x = np.linalg.solve(A, b)
x

array([0. , 0.5])

## Sample Problem

- X1 + X2 = 2200
- 1.5*X1 + 4*X2 = 5050
- Solve for X1 and X2
- Linear equation in terms of matrix
    - Matrix [[1,1], [1.5, 4]] * [X1, X2] = [2200, 5050]

In [136]:
A = np.array([[1,1], [1.5, 4]])
b = np.array([2200, 5050])

In [138]:
x = np.linalg.inv(A).dot(b)
x

array([1500.,  700.])

In [139]:
##Alternatively we can solve like:

x = np.linalg.solve(A, b)
x

array([1500.,  700.])